version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: upivot_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  api:
    build: ./api
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongo

  web:
    build: ./web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api

volumes:
  mongo_data:
